clear;
clc;

N = 1000;                      % sample points
tscale= 0.05;                  % x axis range 
dt = tscale/N;                 % time slot

A = 20;                         % amplitude
f = 100;                       % frequency
phase = 0;                     % phase
t = 0:dt:(N-1)*dt;             % time range
V_s1 = A*sin(2*pi*f*t+phase);    % define a sine wave

%V_s1 = V_s1./max(abs(V_s1));                     % set amplitude rms to always 1
x1 = max(V_s1)./sqrt(2);
V_s1 = V_s1./x1;


elements(1) = nport('sawfilterpassive.s2p');
elements(2) = amplifier(                                                ...
    'Name','LNA',                                                       ...
    'Gain',18,                                                          ...
    'NF',3,                                                             ...
    'OIP3',10);
elements(3) = modulator(                                                ...
    'Name','Demod',                                                     ...
    'Gain',10,                                                          ...
    'NF',6.4,                                                           ...
    'OIP3',36,                                                          ...
    'LO',2.45e9,                                                        ...
    'ConverterType','Down');
elements(4) = amplifier(                                                ...
    'Gain',20,                                                          ...
    'NF',11.3,                                                          ...
    'OIP3',42);

elements(2).Gain = 10;
%plot(amplifier.p2);

